version: "2"
services:
  people_recognition:
    container_name: opencv_findperson
    image: "nidayand/video-people-detection-with-http-post"
    environment: 
      - URLPATH=http://nodered:1880/videonotify
      - CONFIDENCE=0.2
      - GOOD_ENOUGH_CONFIDENCE=0.95
      - FRAMES=1
      - WIDTH=640
      - HEIGHT=480
      - WIDTH_PERSON=40
      - HEIGHT_PERSON=140
      - WIDTH_HEIGHT_RATIO_COMPARE_DIFF=32
      - MAX_SIZE=80
    ports:
      - 8080:8080
    links:
      - "nodered"
  nodered:
    container_name: nodered
    image: nodered/node-red
    ports:
      - 1880:1880
    entrypoint: bash -c "curl https://raw.githubusercontent.com/nidayand/video-people-detection-with-http-post/main/simple-demo.tar.gz | tar -xz -C /data && npm start --cache /data/.npm -- --userDir /data/demo"
